# Note: An AuthorizationPolicy sample is shown below and commented out.
# By not having an AuthorizationPolicy, either API Keys or JWTs can be
# used by clients. If you enable the AuthorizationPolicy, JWT tokens will
# be required and API Keys will not work by themselves.

apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: apigee
  namespace: default
spec:
  selector:
    matchLabels:
      managed-by: apigee
  jwtRules:
  - issuer: {{.JWTProviderKey}}
    jwksUri: https://{{.RuntimeHost}}/remote-service/certs
# ---
# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   name: apigee
#   namespace: default
# spec:
#   selector:
#   matchLabels:
#     managed-by: apigee
#   rules:
#   - from:
#     - source:
#         requestPrincipals: ["*"]